// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mytuwopzcvaexioecyae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15dHV3b3B6Y3ZhZXhpb2VjeWFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMjQ2NTYsImV4cCI6MjA2NTgwMDY1Nn0.MS6pxFrPPDqfjVPRsamUVyq4AzOsYDttMLaDGXiB5PA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);